### PR TITLE
Gp minor doc change

### LINKED ISSUE #452: [BUG] Documentation error
**Describe the bug**

The `render` docstring is missing `postprocess_frame` and `postprocess_frames_flow` in the function signature.

### PR DESCRIPTION
**Pull request by gpucce**
## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [x] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [ ] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [ ] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [ ] Did I properly add test dependencies to the `test` directory (if applicable)?
- [ ] Did I check relevant tutorials that may be affected by changes in this PR?
- [ ] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #452

**How did you address these issues with this PR? What methods did you use?**
I change the docstring

### CODE REVIEW

**Review by TheCedarPrince — CHANGES_REQUESTED** [review]
Could you rebase this on master?
It is tracking your changes from JavisNB and is making edits to Javis.jl and the `javis_viewer` tools which should be in a separate PR.

**Comment by gpucce** [comment]
Yeah sorry I was changing it

**Review by TheCedarPrince — APPROVED** [review]
LGTM - thanks @gpucce! :blue_heart:

**Comment by TheCedarPrince** [comment]
Hey @Wikunia , I went ahead and merged this after review but it seems like our test suite is failing entirely.
Not sure what is going on.
We may need to open up a line of investigation there.
Perhaps there is a compat issue coming up?

**Comment by gpucce** [comment]
Yeah there are two tests that don't pass, however they do pass locally on my machine don't know if this helps anyhow.

**Comment by Wikunia** [comment]
That's good to know. I can check it tmr

**Comment by Wikunia** [comment]
On my machine the tests fail as well but I didn't have the time to check why yet. Will get back to you

**Comment by TheCedarPrince** [comment]
Can confirm they also fail on mine as well.
I will see if I can debug the issue.
In the interim, I will also open an issue to track this.

**Comment by Wikunia** [comment]
Lol I'm pretty sure it's due to my own change in Luxor.jl :smile:
I found a bug in the simplify method but forgot that I used it for morphing as well
https://github.com/JuliaGraphics/Luxor.jl/releases/tag/v2.18.0

**Comment by TheCedarPrince** [comment]
Haha, well awesome that we found it! :smile:

**Pull request merged**
