### PR TITLE
Make new Rotation constructor and redefine anim_rotate[_around]

### LINKED ISSUE #450: [BUG] Irrational and Integer angles fail in rotation Actions
Julia v1.7. Javis v0.7.1

In using Javis I encountered this mysterious behavior:

```
julia> act!(p, Action(1:100, anim_rotate_around(π, p2)))                                                   
ERROR: MethodError: no method matching Javis.Rotation(::Float64, ::Irrational{:π}, ::Object)           

julia> act!(p, Action(1:100, anim_rotate_around(6, p2)))                                                   
ERROR: MethodError: no method matching Javis.Rotation(::Float64, ::Int64, ::Object)                        
```

p and p2 are objects defined as usual with calls to Object().

Same errors using anim_rotate().

Expected behavior: I get the rotations around the requested number of radians.

What happens instead: if the angle is specified as π (Irrational) or an integer, I get a MethodError.

I fixed this in PR #449.

### PR DESCRIPTION
**Pull request by leephillips**
to handle Integer and Irrational rotation angles.

## PR Checklist

If you are contributing to `Javis.jl`, please make sure you are able to check off each item on this list:

- [ ] Did I update `CHANGELOG.md` with whatever changes/features I added with this PR?
- [ ] Did I make sure to only change the part of the file where I introduced a new change/feature?
- [ ] Did I cover all corner cases to be close to 100% test coverage (if applicable)?
- [ ] Did I properly add Javis dependencies to the `Project.toml` + set an upper bound of the dependency (if applicable)?
- [ ] Did I properly add test dependencies to the `test` directory (if applicable)?
- [ ] Did I check relevant tutorials that may be affected by changes in this PR?
- [ ] Did I clearly articulate why this PR was made the way it was and how it was made?

**Link to relevant issue(s)**
Closes #450

**How did you address these issues with this PR? What methods did you use?**

Added a constructor for Rotation that promotes arguments to have the same type;
changed type signatures of anim_rotate_around() and anim_rotate().

### CODE REVIEW

**Comment by TheCedarPrince** [comment]
Hey @leephillips !

Thank you for making this PR and working with @Wikunia on this!
I will let @Wikunia do a review of this more thoroughly as you have been working with him the most on this PR but one thing I notice is that the docstrings for these functions may need to be updated to reflect the new type signatures. 

Also, we try to always recognize all contributors to Javis!
We will be sure to add your name to the list of our contributors in our README before we finish this PR.
You can also do that if you are willing but otherwise, we will take care of it for you.

Thanks @leephillips !

**Comment by leephillips** [comment]
”the docstrings for these functions may need to be updated to reflect the new type signatures.”

Quite right. I updated the docstrings in a new commit.

**Comment by Wikunia** [comment]
Thanks @leephillips 
I've added a line to the changelog and changed your test cases a little bit.

**Review by Wikunia — APPROVED** [review]

**Comment by leephillips** [comment]
Looks good to me.

**Comment by Wikunia** [comment]
Test cases should pass after #455 is merged. :wink:

**Pull request merged**
